#!/usr/bin/env bash

# Build ATS using the /opt/openssl-quic version of OpenSSL.

set -e
set -x
fail()
{
  echo $1
  exit 1
}

cmake -B docs-build --preset ci-docs
cmake --build docs-build --target generate_docs -v
