#!/usr/bin/env bash

# Build ATS using the /opt/openssl-quic version of OpenSSL.

set -e
set -x
expected_dirname="${HOME}/src"
fail()
{
  echo $1
  exit 1
}

openssl="/opt/openssl-quic"

repo_name=`basename $(pwd)`
install_dir="${HOME}/build/${repo_name}"
dirname=$(dirname $(pwd))
[ "${dirname}" = "${expected_dirname}" ] || fail "Expected to be in: ${expected_dirname}. Not running"

# https://github.com/apache/trafficserver/blob/33cc7990a88c1ad04de63fd94f8b937ba50a92e7/ci/jenkins/bin/environment.sh#L77
echo "Building with:"
which clang
export CC=`which clang`
export CXX=`which clang++`
export CXXFLAGS="-Qunused-arguments"
export WITH_LIBCPLUSPLUS="yes"

# Make sure we get the quic-version of curl.
export PATH=/opt/bin:${PATH}
if [ -d "${install_dir}" ]
then
  while true; do
    read -p "${install_dir} already exists. Clean it? (y/n) " yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit 0;;
        * ) echo "Please answer y or n.";;
    esac
  done

  git clean -d -x -f -f -q
  rm -rf ${install_dir}
fi

if [ -f Makefile.am ]
then
  autoreconf -fi
  ./configure --prefix ${install_dir} --with-openssl=${openssl} --enable-experimental-plugins --enable-example-plugins
  bear -- make -j8 install
else
  build_dir="build"
  cmake \
    -G Ninja \
    -B ${build_dir} \
    -DCMAKE_BUILD_TYPE=Debug \
    -DOPENSSL_ROOT_DIR=${openssl} \
    -DCMAKE_INSTALL_PREFIX=${install_dir} \
    -DBUILD_EXPERIMENTAL_PLUGINS=ON \
    -DENABLE_EXAMPLE=ON \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON\
    -DCMAKE_COMPILE_WARNING_AS_ERROR=ON \
    -DENABLE_AUTEST=ON

  cmake --build ${build_dir}
  cmake --install ${build_dir}
fi
