#!/usr/bin/env bash

fail()
{
  echo "Failed: $*"
  exit 1
}

[ $# -eq 1 ] || fail "Usage: $0 <new_repo_name>"
repo_name=$1
[ -d $repo_name ] && fail "Repo $repo_name already exists"

git clone git@git.ouryahoo.com:bneradt/trafficserver.git ${repo_name}
cd ${repo_name}
git remote add upstream git@git.ouryahoo.com:Edge/trafficserver.git
git remote update

git pull upstream 10.0.x
git push origin 10.0.x
