#!/bin/bash

if [ -n "$(compgen -G '/tmp/cursor-remote-ssh-*')" ]
then
    # Cursor
    SSH_AUTH_SOCK=$(ls -tr /tmp/cursor-remote-ssh-* 2>/dev/null | tail -1)
    if [ -n "${SSH_AUTH_SOCK}" ]
    then
        export SSH_AUTH_SOCK
    fi
elif [ -n "$(compgen -G '/tmp/vscode-ssh-auth-*')" ]
then
    # VSCode
    SSH_AUTH_SOCK=$(ls -tr /tmp/vscode-ssh-auth-* 2>/dev/null | tail -1)
    if [ -n "${SSH_AUTH_SOCK}" ]
    then
        export SSH_AUTH_SOCK
    fi
else
    echo "Could not find the socket to set SSH_AUTH_SOCK to."
fi
