#!/usr/bin/env bash

script_name=$(basename $0)
usage="${script_name} \<new_docker_image_name\> \"\<Git Full Name\>\" \<git.user@email.com\> \<Git User Name\>"

tmpdir=/tmp/docker_image_create_$$

fail()
{
  echo $1
  exit 1
}

[ $# -eq 4 ] || fail "${usage}"
tag_name=$1; shift
git_full_name=$1; shift
git_email=$1; shift
username=$1; shift

parent_dir=$(dirname $0)
ats_dockerfile_dir=${parent_dir}/../Dockerfiles/ats
[ -d "${ats_dockerfile_dir}" ] || fail "Could not find ATS Dockerfile: ${ats_dockerfile_dir}"

context_dir=${parent_dir}/../docker_context
[ -d "${context_dir}" ] || fail "Could not find ATS context directory: ${context_dir}"

set -x
set -e
mkdir -p ${tmpdir}
cp -rf ${ats_dockerfile_dir}/* ${tmpdir}
cp -rf ${context_dir}/.[^.]* ${tmpdir}
cp -rf ${context_dir}/* ${tmpdir}
cp -rf ${context_dir}/fedora/.[^.]* ${tmpdir}

cd $tmpdir
docker build \
  --ssh default \
  -t ${tag_name} \
  --build-arg "username=${username}" \
  --build-arg "userid=$(id -u)" \
  --build-arg "git_username=$git_full_name" \
  --build-arg "git_email=$git_email" \
  .

rm -rf $tmpdir
