#!/usr/bin/env bash

usage="$(basename $0) <docker_image> <container_name>"

fail()
{
  echo $1
  exit 1
}

set -e

[ -n "${HOME}" ] || fail "HOME is not set."
[ $# -eq 2 ] || fail "Not enough parameters: ${usage}"
docker_image=${1}; shift
container_name=${1}; shift

# Select a random free port.
free_port=`netstat -aln | awk '
  $6 == "LISTEN" {
    if ($4 ~ "[.:][0-9]+$") {
      split($4, a, /[:.]/);
      port = a[length(a)];
      p[port] = 1
    }
  }
  END {
    srand();
    start = int(3000 + rand()*10000);
    for (i = start; i < 65000 && p[i]; i++){};
    if (i == 65000) {exit 1};
    print i
  }
'`

YUBI_ARGUMENT=""
if [ -d ${HOME}/.yubiagent ]
then
  YUBI_ARGUMENT="-v /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock -v ${HOME}/.ssh/sshca:/home/bneradt/.ssh/sshca -e SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock"
fi
docker run \
  --name ${container_name} \
  --init \
  --cap-add=SYS_PTRACE \
  -p ${free_port}:8888 \
  -u $(whoami) \
  -d \
  -t \
  -v ${HOME}/.ssh:/home/$(whoami)/.ssh:Z \
  ${YUBI_ARGUMENT} \
  ${docker_image}

branch_name=${container_name}
docker exec -u $(whoami) ${container_name} /home/$(whoami)/bin/start_ats_project ${branch_name}

echo
echo "Enter the container with:"
echo "docker exec -it -u $(whoami) ${container_name} /bin/bash"
echo
echo "Enter the tmux session with:"
echo "tmux attach -t ${branch_name}"
