#!/usr/bin/env bash

usage="$(basename $0) <docker_image> <container_name>"

fail()
{
  echo $1
  exit 1
}

set -e

[ -n "${HOME}" ] || fail "HOME is not set."
[ $# -eq 2 ] || fail "Not enough parameters: ${usage}"
docker_image=${1}; shift
container_name=${1}; shift

YUBI_ARGUMENT=""
if [ -d ${HOME}/.yubiagent ]
then
  YUBI_ARGUMENT="-v /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock -v ${HOME}/.ssh/sshca:/home/${docker_username}/.ssh/sshca -e SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock"
fi

docker run \
  --name ${container_name} \
  --init \
  --cap-add=SYS_PTRACE \
  --network=host \
  -u $(whoami) \
  -d \
  -t \
  -v ${HOME}/.ssh:/home/$(whoami)/.ssh:Z \
  ${YUBI_ARGUMENT} \
  ${docker_image}

branch_name=${container_name}
docker exec -u $(whoami) ${container_name} /home/$(whoami)/bin/start_proxy_verifier_project ${branch_name}

echo
echo "Enter the container with:"
echo "docker exec -it -u $(whoami) ${container_name} /bin/zsh"
echo
echo "Enter the tmux session with:"
echo "tmux attach -t ${branch_name}"
